import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Index: NextPage = () => {
  return (
    <div className={`container`}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe
        width="560"
        height="315"
        src="https://www.youtube.com/embed/GGe_h2MWMrs"
        title="YouTube video player"
        frameBorder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowFullScreen
      ></iframe>
    </div>
  );
};

export default Index;
