import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Index: NextPage = () => {
  return (
    <div className={`container`}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Index;
